spring:
  kafka:
    bootstrap-servers: kafka-service:9092
  datasource:
    url: jdbc:postgresql://payment-db:5432/payment
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always