kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.1
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: kafka-config